INSERT INTO categories (test_code, name, weight_percent)
SELECT 'DISC_FREE', seed.name, seed.weight_percent
FROM (VALUES
  ('Ra quyết định', 12),
  ('Giao tiếp', 13),
  ('Làm việc nhóm', 12),
  ('Áp lực và xung đột', 13),
  ('Kỷ luật và quy trình', 12),
  ('Thay đổi và học hỏi', 13),
  ('Lãnh đạo và trách nhiệm', 12),
  ('Lập kế hoạch và thực thi', 13)
) AS seed(name, weight_percent)
WHERE NOT EXISTS (
  SELECT 1
  FROM categories existing
  WHERE existing.test_code = 'DISC_FREE' AND existing.name = seed.name
);

INSERT INTO questions (test_code, category_id, content, trait_key, reverse_scored, weight, order_index)
SELECT 'DISC_FREE', category_map.id, seed.content, seed.trait_key, FALSE, 1.0, seed.order_index
FROM (VALUES
  (1, 'Ra quyết định', 'Khi nhận một mục tiêu mới, phản ứng tự nhiên nhất của bạn là gì?', 'DISC_D'),
  (2, 'Ra quyết định', 'Khi có hai phương án khá ngang nhau, bạn thường nghiêng về cách nào?', 'DISC_D'),
  (3, 'Ra quyết định', 'Khi phải quyết định mà thời gian ít và thông tin chưa đủ, bạn hay làm gì?', 'DISC_D'),
  (4, 'Ra quyết định', 'Khi thấy một cơ hội mới xuất hiện, bạn thường nghĩ gì đầu tiên?', 'DISC_D'),
  (5, 'Ra quyết định', 'Khi bị yêu cầu chọn ngay một hướng đi, bạn thường làm gì?', 'DISC_D'),
  (6, 'Giao tiếp', 'Trong một buổi họp đông người, bạn thường thể hiện thế nào?', 'DISC_D'),
  (7, 'Giao tiếp', 'Khi cần góp ý cho đồng nghiệp, bạn thường chọn cách nào?', 'DISC_D'),
  (8, 'Giao tiếp', 'Khi giới thiệu một ý tưởng mới, bạn thiên về cách nào?', 'DISC_D'),
  (9, 'Giao tiếp', 'Khi ai đó không đồng ý với bạn, phản ứng thường thấy nhất của bạn là gì?', 'DISC_D'),
  (10, 'Giao tiếp', 'Khi viết một email quan trọng, bạn thường ưu tiên điều gì?', 'DISC_D'),
  (11, 'Làm việc nhóm', 'Trong một nhóm mới, bạn thường vào vai nào trước tiên?', 'DISC_D'),
  (12, 'Làm việc nhóm', 'Khi phân chia công việc cho nhóm, bạn hay ưu tiên điều gì?', 'DISC_D'),
  (13, 'Làm việc nhóm', 'Khi một đồng đội làm chậm tiến độ, bạn thường làm gì?', 'DISC_D'),
  (14, 'Làm việc nhóm', 'Khi cả nhóm đạt được kết quả tốt, điều bạn thường làm là gì?', 'DISC_D'),
  (15, 'Làm việc nhóm', 'Khi phải phối hợp với phòng ban khác, bạn thường theo cách nào?', 'DISC_D'),
  (16, 'Áp lực và xung đột', 'Khi deadline rất sát, cách làm quen thuộc nhất của bạn là gì?', 'DISC_D'),
  (17, 'Áp lực và xung đột', 'Khi bị phản đối gay gắt, bạn thường phản ứng thế nào?', 'DISC_D'),
  (18, 'Áp lực và xung đột', 'Khi phát sinh một sự cố bất ngờ, bạn thường xử lý theo hướng nào?', 'DISC_D'),
  (19, 'Áp lực và xung đột', 'Khi khối lượng việc vượt quá khả năng trong ngắn hạn, bạn hay làm gì?', 'DISC_D'),
  (20, 'Áp lực và xung đột', 'Khi trong nhóm có mâu thuẫn, bạn thường chọn cách nào?', 'DISC_D'),
  (21, 'Kỷ luật và quy trình', 'Khi nhận một việc chưa có hướng dẫn rõ, bạn thường làm gì?', 'DISC_D'),
  (22, 'Kỷ luật và quy trình', 'Với một lỗi nhỏ nhưng lặp lại nhiều lần, bạn thường xử lý ra sao?', 'DISC_D'),
  (23, 'Kỷ luật và quy trình', 'Khi bàn giao công việc cho người khác, bạn thường làm theo cách nào?', 'DISC_D'),
  (24, 'Kỷ luật và quy trình', 'Khi đánh giá chất lượng một đầu việc, bạn chú ý điều gì nhất?', 'DISC_D'),
  (25, 'Kỷ luật và quy trình', 'Khi có một quy định mới được ban hành, bạn thường phản ứng thế nào?', 'DISC_D'),
  (26, 'Thay đổi và học hỏi', 'Khi có một công cụ mới xuất hiện, bạn thường tiếp cận ra sao?', 'DISC_D'),
  (27, 'Thay đổi và học hỏi', 'Khi phải đổi một cách làm quen thuộc, bạn thường như thế nào?', 'DISC_D'),
  (28, 'Thay đổi và học hỏi', 'Khi học một kỹ năng mới, bạn thường chọn cách học nào?', 'DISC_D'),
  (29, 'Thay đổi và học hỏi', 'Khi thị trường hoặc bối cảnh thay đổi, phản ứng đầu tiên của bạn là gì?', 'DISC_D'),
  (30, 'Thay đổi và học hỏi', 'Khi nhận được feedback mới từ khách hàng, bạn thường ưu tiên gì?', 'DISC_D'),
  (31, 'Lãnh đạo và trách nhiệm', 'Khi không ai đứng ra nhận một việc khó, bạn thường làm gì?', 'DISC_D'),
  (32, 'Lãnh đạo và trách nhiệm', 'Khi dẫn dắt một nhóm, bạn thường nghiêng về cách nào?', 'DISC_D'),
  (33, 'Lãnh đạo và trách nhiệm', 'Khi một thành viên yếu hơn kỳ vọng, bạn thường xử lý thế nào?', 'DISC_D'),
  (34, 'Lãnh đạo và trách nhiệm', 'Khi giao mục tiêu quý cho đội, bạn thường làm theo cách nào?', 'DISC_D'),
  (35, 'Lãnh đạo và trách nhiệm', 'Khi phải xử lý một người làm sai, bạn thường chọn cách nào?', 'DISC_D'),
  (36, 'Lập kế hoạch và thực thi', 'Khi lập kế hoạch tháng, bạn thường ưu tiên điều gì?', 'DISC_D'),
  (37, 'Lập kế hoạch và thực thi', 'Khi theo dõi tiến độ thực hiện, bạn thường làm thế nào?', 'DISC_D'),
  (38, 'Lập kế hoạch và thực thi', 'Khi phải triển khai nhiều đầu việc cùng lúc, bạn thường làm gì?', 'DISC_D'),
  (39, 'Lập kế hoạch và thực thi', 'Khi một kế hoạch không đạt như mong muốn, bạn thường phản ứng ra sao?', 'DISC_D'),
  (40, 'Lập kế hoạch và thực thi', 'Khi chốt một đợt triển khai, bạn thường chú ý điều gì nhất?', 'DISC_D')
) AS seed(order_index, category_name, content, trait_key)
JOIN categories category_map
  ON category_map.test_code = 'DISC_FREE' AND category_map.name = seed.category_name
WHERE NOT EXISTS (
  SELECT 1
  FROM questions existing
  WHERE existing.test_code = 'DISC_FREE' AND existing.order_index = seed.order_index
);

INSERT INTO question_options (question_id, label, value, disc_dimension, order_index)
SELECT question_map.id, seed.label, 1, seed.disc_dimension, seed.order_index
FROM (VALUES
  (1, 'Chốt đích và đẩy tốc độ thực hiện', 'D', 1),
  (1, 'Tạo năng lượng để mọi người cùng vào việc', 'I', 2),
  (1, 'Tìm cách làm ít xáo trộn nhất', 'S', 3),
  (1, 'Xác định tiêu chuẩn và rủi ro trước', 'C', 4),
  (2, 'Phương án dễ tạo đồng thuận và hứng khởi', 'I', 1),
  (2, 'Phương án có dữ liệu chắc nhất', 'C', 2),
  (2, 'Phương án tạo tác động mạnh hơn', 'D', 3),
  (2, 'Phương án ổn định và ít rủi ro hơn', 'S', 4),
  (3, 'Giữ nhịp an toàn để tránh sai lớn', 'S', 1),
  (3, 'Quyết nhanh theo mục tiêu chính', 'D', 2),
  (3, 'Thu thập thêm vài dữ kiện mấu chốt rồi chốt', 'C', 3),
  (3, 'Trao đổi nhanh với người liên quan để có thêm góc nhìn', 'I', 4),
  (4, 'Kiểm tra tính khả thi trước', 'C', 1),
  (4, 'Xem nó có làm xáo trộn hệ thống hiện tại không', 'S', 2),
  (4, 'Nghĩ cách lan tỏa để kéo người khác tham gia', 'I', 3),
  (4, 'Muốn chớp lấy trước khi cơ hội qua đi', 'D', 4),
  (5, 'Nhận trách nhiệm và ra quyết định luôn', 'D', 1),
  (5, 'Tìm cách giữ mọi người cùng ủng hộ quyết định đó', 'I', 2),
  (5, 'Chọn hướng ít gây căng thẳng nhất cho tập thể', 'S', 3),
  (5, 'Kiểm tra các điều kiện then chốt trước khi gật đầu', 'C', 4),
  (6, 'Nói để tạo không khí và kết nối mọi người', 'I', 1),
  (6, 'Chỉ phát biểu khi có luận điểm rõ ràng', 'C', 2),
  (6, 'Nói thẳng điều cần làm và việc cần chốt', 'D', 3),
  (6, 'Lắng nghe kỹ rồi chọn thời điểm phù hợp để nói', 'S', 4),
  (7, 'Nói nhẹ nhàng để họ dễ tiếp nhận', 'S', 1),
  (7, 'Đi thẳng vào vấn đề và kỳ vọng', 'D', 2),
  (7, 'Đưa ví dụ và dẫn chứng cụ thể', 'C', 3),
  (7, 'Bắt đầu bằng sự khích lệ và tương tác cởi mở', 'I', 4),
  (8, 'Chuẩn bị kỹ cấu trúc và số liệu', 'C', 1),
  (8, 'Chú ý cảm giác người nghe và nhịp trao đổi', 'S', 2),
  (8, 'Kể theo cách cuốn hút và dễ lan tỏa', 'I', 3),
  (8, 'Nhấn mạnh vào lợi ích và kết quả phải đạt', 'D', 4),
  (9, 'Tranh luận để làm rõ hướng đúng', 'D', 1),
  (9, 'Tìm điểm chung để kéo họ về phía mình', 'I', 2),
  (9, 'Giữ bình tĩnh để tránh căng thẳng thêm', 'S', 3),
  (9, 'Quay lại tiêu chí và bằng chứng', 'C', 4),
  (10, 'Giọng điệu tích cực và dễ tạo thiện cảm', 'I', 1),
  (10, 'Nội dung chặt chẽ và ít kẽ hở', 'C', 2),
  (10, 'Ngắn gọn rõ ràng và chốt hành động', 'D', 3),
  (10, 'Lịch sự mềm mại để thuận hợp tác', 'S', 4),
  (11, 'Quan sát để hòa nhịp trước', 'S', 1),
  (11, 'Nhận phần việc khó hoặc phần quyết định', 'D', 2),
  (11, 'Làm rõ vai trò và nguyên tắc làm việc', 'C', 3),
  (11, 'Kết nối mọi người thật nhanh', 'I', 4),
  (12, 'Phân theo năng lực và chuẩn đầu ra', 'C', 1),
  (12, 'Phân sao cho mọi người giữ được nhịp bền', 'S', 2),
  (12, 'Phân sao cho nhóm có khí thế và tương tác tốt', 'I', 3),
  (12, 'Phân để tốc độ và kết quả lên cao nhất', 'D', 4),
  (13, 'Thúc để tiến độ quay lại ngay', 'D', 1),
  (13, 'Động viên để họ có lại tinh thần', 'I', 2),
  (13, 'Hỗ trợ họ xử lý từng phần', 'S', 3),
  (13, 'Soát nguyên nhân và điểm nghẽn cụ thể', 'C', 4),
  (14, 'Chia sẻ và ăn mừng cùng mọi người', 'I', 1),
  (14, 'Ghi nhận đúng đóng góp và số liệu', 'C', 2),
  (14, 'Chốt ngay bước tiếp theo cần làm', 'D', 3),
  (14, 'Cảm ơn từng người và giữ nhịp ổn định', 'S', 4),
  (15, 'Giữ thái độ mềm để đôi bên dễ làm việc', 'S', 1),
  (15, 'Đẩy rõ deadline và đầu mối trách nhiệm', 'D', 2),
  (15, 'Làm rõ quy trình bàn giao và điều kiện nghiệm thu', 'C', 3),
  (15, 'Chủ động tạo quan hệ để xử lý nhanh hơn', 'I', 4),
  (16, 'Cắt bớt việc và siết chuẩn đầu ra', 'C', 1),
  (16, 'Giữ nhịp ổn định để tránh rối thêm', 'S', 2),
  (16, 'Truyền lửa để mọi người tăng tốc', 'I', 3),
  (16, 'Ưu tiên chốt việc quan trọng trước thật quyết liệt', 'D', 4),
  (17, 'Phản biện ngay nếu thấy chưa đúng', 'D', 1),
  (17, 'Làm dịu không khí rồi dẫn lại vấn đề', 'I', 2),
  (17, 'Kiềm chế để tránh xung đột leo thang', 'S', 3),
  (17, 'Yêu cầu quay về dữ kiện và tiêu chí', 'C', 4),
  (18, 'Gọi đúng người vào để xử lý thật nhanh', 'I', 1),
  (18, 'Khoanh vùng nguyên nhân theo cách có hệ thống', 'C', 2),
  (18, 'Quyết ngay phương án khẩn cấp', 'D', 3),
  (18, 'Giữ đội bình tĩnh và bám nhịp quen thuộc', 'S', 4),
  (19, 'Giảm nhiễu và làm lần lượt cho chắc', 'S', 1),
  (19, 'Dám bỏ phần ít quan trọng để đạt mục tiêu chính', 'D', 2),
  (19, 'Lập lại ưu tiên và checklist chi tiết', 'C', 3),
  (19, 'Trao đổi để kéo thêm hỗ trợ hoặc nguồn lực', 'I', 4),
  (20, 'Tìm sự thật và nguyên nhân cụ thể trước', 'C', 1),
  (20, 'Ưu tiên giữ quan hệ để nhóm không vỡ nhịp', 'S', 2),
  (20, 'Đứng ra nói chuyện để hai bên mở hơn', 'I', 3),
  (20, 'Cắt thẳng vào vấn đề và chốt cách xử lý', 'D', 4),
  (21, 'Làm thử nhanh để có kết quả sớm', 'D', 1),
  (21, 'Hỏi thêm ngữ cảnh từ người liên quan', 'I', 2),
  (21, 'Tìm cách làm ít rủi ro nhất', 'S', 3),
  (21, 'Tự dựng quy trình hoặc checklist trước', 'C', 4),
  (22, 'Nhắc mọi người và kéo họ cùng sửa', 'I', 1),
  (22, 'Tìm gốc lỗi để chặn tận nơi', 'C', 2),
  (22, 'Xử lý dứt điểm càng sớm càng tốt', 'D', 3),
  (22, 'Theo dõi đều và chỉnh dần cho ổn', 'S', 4),
  (23, 'Bàn giao cẩn thận để người sau dễ tiếp nhận', 'S', 1),
  (23, 'Nói rõ mục tiêu hạn chót và trách nhiệm', 'D', 2),
  (23, 'Ghi lại bước làm tài liệu và tiêu chuẩn', 'C', 3),
  (23, 'Trao đổi trực tiếp để tạo phối hợp tốt', 'I', 4),
  (24, 'So với tiêu chí và dữ liệu đầu ra', 'C', 1),
  (24, 'Xem việc vận hành có ổn định không', 'S', 2),
  (24, 'Xem phản hồi của người dùng hoặc đội ngũ', 'I', 3),
  (24, 'Xem nó có đạt mục tiêu kinh doanh không', 'D', 4),
  (25, 'Áp dụng ngay nếu thấy nó giúp hiệu suất hơn', 'D', 1),
  (25, 'Giải thích để mọi người cùng hiểu và theo', 'I', 2),
  (25, 'Muốn có thời gian làm quen dần', 'S', 3),
  (25, 'Muốn đọc kỹ trước khi thực hiện', 'C', 4),
  (26, 'Hào hứng thử và chia sẻ cho người khác', 'I', 1),
  (26, 'Đọc kỹ hướng dẫn và so sánh tính năng trước', 'C', 2),
  (26, 'Dùng ngay để xem có tạo kết quả không', 'D', 3),
  (26, 'Chỉ chuyển sang khi thật sự cần và ổn định', 'S', 4),
  (27, 'Cần một chút thời gian để thích nghi', 'S', 1),
  (27, 'Sẵn sàng bỏ cách cũ nếu cách mới hiệu quả hơn', 'D', 2),
  (27, 'Muốn hiểu rõ logic và rủi ro của thay đổi', 'C', 3),
  (27, 'Thấy hứng thú vì có cái mới để khám phá', 'I', 4),
  (28, 'Học có lộ trình và chuẩn đánh giá rõ', 'C', 1),
  (28, 'Học đều đặn từng bước chắc chắn', 'S', 2),
  (28, 'Học qua trao đổi workshop và cộng đồng', 'I', 3),
  (28, 'Học thứ có thể áp dụng ra kết quả nhanh nhất', 'D', 4),
  (29, 'Chủ động điều chỉnh mục tiêu sớm', 'D', 1),
  (29, 'Tìm cách truyền thông để đội không hụt nhịp', 'I', 2),
  (29, 'Ưu tiên giữ phần lõi đang vận hành tốt', 'S', 3),
  (29, 'Phân tích tác động rồi mới đổi lớn', 'C', 4),
  (30, 'Trao đổi ngay để hiểu cảm xúc và kỳ vọng của họ', 'I', 1),
  (30, 'Gom dữ liệu đủ mẫu rồi mới kết luận', 'C', 2),
  (30, 'Chốt thay đổi nào tạo hiệu quả nhanh nhất', 'D', 3),
  (30, 'Chỉnh vừa phải để không phá ổn định', 'S', 4),
  (31, 'Nhận phần hỗ trợ để đội bớt áp lực', 'S', 1),
  (31, 'Đứng ra cầm việc ngay', 'D', 2),
  (31, 'Làm rõ phạm vi và điều kiện thành công trước', 'C', 3),
  (31, 'Kêu gọi mọi người cùng nhập cuộc', 'I', 4),
  (32, 'Quản trị bằng KPI chuẩn chất lượng và tiến độ', 'C', 1),
  (32, 'Giữ đội ổn định và ít va chạm không cần thiết', 'S', 2),
  (32, 'Tạo tinh thần và niềm tin cho mọi người', 'I', 3),
  (32, 'Đẩy đội hướng tới mục tiêu lớn rõ và nhanh', 'D', 4),
  (33, 'Nói thẳng điểm cần nâng lên', 'D', 1),
  (33, 'Tạo động lực và truyền niềm tin cho họ', 'I', 2),
  (33, 'Kèm cặp đều để họ bắt nhịp lại', 'S', 3),
  (33, 'Chỉ rõ chuẩn đầu ra và cách đo', 'C', 4),
  (34, 'Trình bày theo cách khiến đội hào hứng', 'I', 1),
  (34, 'Chia nhỏ thành tiêu chí và mốc đo cụ thể', 'C', 2),
  (34, 'Đặt mục tiêu đủ thách thức và đẩy tiến độ', 'D', 3),
  (34, 'Cân đối để đội giữ được nhịp bền vững', 'S', 4),
  (35, 'Trao đổi riêng mềm nhưng rõ', 'S', 1),
  (35, 'Quyết liệt nếu lỗi ảnh hưởng kết quả chung', 'D', 2),
  (35, 'Xem lại quy trình bằng chứng và trách nhiệm', 'C', 3),
  (35, 'Nói theo cách giúp họ sẵn sàng sửa hơn', 'I', 4),
  (36, 'Lập mốc số đo rủi ro và phương án dự phòng', 'C', 1),
  (36, 'Giữ kế hoạch vừa sức và bám được lâu dài', 'S', 2),
  (36, 'Thêm các điểm tương tác để đội có động lực', 'I', 3),
  (36, 'Ưu tiên hạng mục tạo tác động lớn nhất', 'D', 4),
  (37, 'So với mục tiêu và can thiệp ngay khi lệch', 'D', 1),
  (37, 'Thường xuyên hỏi han để giữ kết nối với đội', 'I', 2),
  (37, 'Bám nhịp đều và tránh đổi quá nhiều', 'S', 3),
  (37, 'Cập nhật bằng số liệu và checkpoint rõ ràng', 'C', 4),
  (38, 'Họp nhanh để đồng bộ người liên quan', 'I', 1),
  (38, 'Chia theo mức ưu tiên phụ thuộc và rủi ro', 'C', 2),
  (38, 'Cắt bớt để giữ tốc độ ở việc quan trọng nhất', 'D', 3),
  (38, 'Giữ thứ tự quen thuộc để tránh rối', 'S', 4),
  (39, 'Bình tĩnh xem lại từng bước đã làm', 'S', 1),
  (39, 'Đổi cách tiếp cận ngay nếu cần', 'D', 2),
  (39, 'Phân tích nguyên nhân bằng dữ liệu và quy trình', 'C', 3),
  (39, 'Trao đổi rộng hơn để tìm thêm ý tưởng', 'I', 4),
  (40, 'Đối chiếu kỹ với tiêu chí nghiệm thu', 'C', 1),
  (40, 'Xem người vận hành sau đó có dễ tiếp quản không', 'S', 2),
  (40, 'Chia sẻ kết quả để tạo khí thế cho chặng sau', 'I', 3),
  (40, 'Chốt bài học và mục tiêu tiếp theo thật nhanh', 'D', 4)
) AS seed(question_order_index, label, disc_dimension, order_index)
JOIN questions question_map
  ON question_map.test_code = 'DISC_FREE' AND question_map.order_index = seed.question_order_index
WHERE NOT EXISTS (
  SELECT 1
  FROM question_options existing
  WHERE existing.question_id = question_map.id
);
